<?php
/**
 * @file
  * Contains trending.module
  */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help()
 */
function trending_help($route_name, RouteMatchInterface $route_match) {
  switch($route_name) {
    //Main Module help for the Trending module
    case 'help.page.trending':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Get Youtube Trending Videos through tags and in different nodes') . '</p>';
      return $output;

      default: 
  }
}

